fix: correctly deserialize string-based enums in XML protocols
smithy-lang/smithy-kotlin pull request #1136
Opened 2024-08-05 21:06 UTC by lauzadis

We were not distinguishing between strings and string-based enums when generating the parser for XML protocols. This PR updates the codegen to treat string shapes with the `EnumTrait` as enums.  

## Issue \#

Closes https://github.com/smithy-lang/smithy-kotlin/issues/1125

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-06 16:20 UTC, 0marperez commented on codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/XmlParserGenerator.kt
> +                println("Shape ${member.defaultName()} is a string! textExprIsResult is $textExprIsResult")
nit: it looks like there are some leftover print statements throughout the pr

2024-08-06 16:58 UTC, ianbotsf requested changes
**Correctness**: Add new test(s) to cover this behavior (possibly protocol or E2E).

2024-08-06 16:58 UTC, ianbotsf commented on codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/XmlParserGenerator.kt
> +                println("Shape ${member.defaultName()} is a string! textExprIsResult is $textExprIsResult")
**Nit**: Remove this and other `println`s.

2024-08-06 16:58 UTC, ianbotsf commented on codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/serde/XmlParserGenerator.kt
>              }
**Suggestion**: Replace `ShapeType.ENUM || (target.type == ShapeType.STRING && target.hasTrait<EnumTrait>())` with [`target.isStringEnumShape`](https://github.com/smithy-lang/smithy-kotlin/blob/1a656f4100a126a236f092a960ead7ba75cfee24/codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/ShapeExt.kt#L163-L174). Also, move it up above the general string case and then you can simplify that branch to just `target.type == StringType.String`.

2024-08-08 20:39 UTC, ianbotsf approved these changes

2024-08-08 21:09 UTC, 0marperez approved these changes

2024-08-08 21:21 UTC, merged